openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0

servers:
    - url: https://task-management-api-ih36.onrender.com

paths:
  /auth/signup:
    post:
      summary: Signup user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        201:
          description: User created

  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login success

  /projects:
    get:
      summary: Get all projects
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of projects

    post:
      summary: Create project
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        201:
          description: Project created

  /tasks:
    get:
      summary: Get all tasks
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of tasks

    post:
      summary: Create task
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                projectId:
                  type: integer
      responses:
        201:
          description: Task created

  /comments:
    get:
      summary: Get all comments
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of comments

    post:
      summary: Create comment
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                taskId:
                  type: integer
      responses:
        201:
          description: Comment created

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT